#do we really need 9090?
server:
  9090
spring:
  application:
    name: mongodbapp
data:
  mongodb:
    host: mongodb
    port: 27017
    username: rootuser
    password: rootpass
    database: comments
    authentication-source: admin
    auto-index-creation: Yes