services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    command: mongod
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  view-app:
    build:
      context: .
      dockerfile: Dockerfile-view
    container_name: view-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - mongodb
      - rabbitmq
  write-app:
    build:
      context: .
      dockerfile: Dockerfile-write
    container_name: write-app
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - rabbitmq
      - mongodb
  mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile-mongodb-app
    container_name: mongodb-app
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  data: {}

networks:
  spring:
    driver: bridge
#  mongodb:
#    name: mongodb_network
