server:
  port: 8080

rabbitmq:
  port: 5672
#  exchanges:
#    internal: internal.exchange
  queues:
    mongodb: mongodb.queue
#  routing-keys:
#    internal-notification: internal.notification.routing-key