rabbitmq:
  exchanges:
    view: view.fan
    receiver: receiver.topic
  queues:
    receiver: receiver.queue
    view: view.queue
  routing-keys:
    receiver: receiver.routing-key

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672