server:
  port: 8088

#spring:
#  application:
#    name: receiver

#rabbitmq:
#  port: 5672
#  exchanges:
#    receiver: receiver.topic
#  queues:
#    receiver: receiver.queue
#  routing-keys:
#    receiver: receiver.routing-key
