server:
  port: 8088

#spring:
#  application:
#    name: receiver

rabbitmq:
  port: 5672
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
