server:
  port: 8088

spring:
  application:
    name: example-module
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: databasename
      port: 27017
      auto-index-creation: true
#  rabbitmq:
#    addresses: rabbitmq:5672
rabbitmq:
  port: 5672
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
