server:
  port: 8080

spring:
  application:
    name: exampleModule
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: databasename
      port: 27017
      auto-index-creation: true

